/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 model.gltf 
*/

import React, { forwardRef, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Model = (props, ref) => {
  const { nodes, materials } = useGLTF('./models/model.gltf')
  return (
    <group
      ref={ref}
      {...props}
      dispose={null}
    >
      <group
        position={[0, 0.519, 0]}
        scale={0.103}
      >
        <mesh
          geometry={nodes.Circle001.geometry}
          // material={materials['Frame.001']}
        >
          <meshPhysicalMaterial
            color={'#343b53'}
            // roughness={0.1}
            clearcoat={1}
            clearcoatRoughness={0.1}
            metalness={0.9}
            roughness={0.5}
          />
        </mesh>
        <mesh
          geometry={nodes.Circle001_1.geometry}
          // material={materials['Frame.001']}
        >
          <meshPhysicalMaterial
            color={'#343b53'}
            // roughness={0.1}
            clearcoat={1}
            clearcoatRoughness={0.1}
            metalness={0.9}
            roughness={0.5}
          />
        </mesh>
        <mesh
          geometry={nodes.Circle001_2.geometry}
          material={materials.HeadPhoneHole}
        />
        <mesh
          geometry={nodes.Circle001_3.geometry}
          material={materials.USB_C_INSIDE}
        />
        <mesh
          geometry={nodes.Circle001_4.geometry}
          material={materials['Frame.001']}
        />
        <mesh
          geometry={nodes.Circle001_5.geometry}
          material={materials.TouchbarBorder}
        />
        <mesh
          geometry={nodes.Circle001_6.geometry}
          material={materials.Keyboard}
        />
        <group
          position={[0, -0.509, 0]}
          scale={5.796}
        >
          <mesh
            geometry={nodes.Circle006.geometry}
            material={materials['Frame.001']}
          />
          <mesh
            geometry={nodes.Circle006_1.geometry}
            material={materials.USB_C_INSIDE}
          />
        </group>
        <mesh
          geometry={nodes.FrontCameraRing001.geometry}
          material={materials['CameraRIngBlack.002']}
          position={[-0.155, 19.571, -16.151]}
          scale={0}
        />
        <group
          position={[-11.786, -0.15, -8.301]}
          scale={5.796}
        >
          <mesh
            geometry={nodes.Circle.geometry}
            material={materials['Keyboard.001']}
          />
          <mesh
            geometry={nodes.Circle_1.geometry}
            material={materials.Key}
          />
          <mesh
            geometry={nodes.Circle_2.geometry}
            material={materials.Touchbar}
          />
        </group>
        <mesh
          geometry={nodes.KeyboardKeyHole.geometry}
          material={materials['Keyboard.001']}
          position={[-11.786, -0.152, -8.301]}
          scale={5.796}
        />
        <mesh
          geometry={nodes.RubberFoot.geometry}
          material={materials.DarkRubber}
          position={[-11.951, -0.751, 7.857]}
          scale={5.796}
        />
        <group
          position={[0.011, -0.211, -10.559]}
          scale={5.796}
        >
          <mesh
            geometry={nodes.Circle012.geometry}
            material={materials.HingeBlack}
          />
          <mesh
            geometry={nodes.Circle012_1.geometry}
            material={materials.HingeMetal}
          />
        </group>
        <group
          position={[-15.026, 0.031, 0.604]}
          scale={5.796}
        >
          <mesh
            geometry={nodes.Circle009.geometry}
            material={materials['Frame.001']}
          />
          <mesh
            geometry={nodes.Circle009_1.geometry}
            material={materials.SpeakerHole}
          />
        </group>
        <group
          position={[12.204, 0.031, 0.604]}
          scale={5.796}
        >
          <mesh
            geometry={nodes.Circle003.geometry}
            material={materials['Frame.001']}
          />
          <mesh
            geometry={nodes.Circle003_1.geometry}
            material={materials.SpeakerHole}
          />
        </group>
        <group
          position={[0.007, -0.472, -10.412]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[5.796, 5.796, 5.716]}
        >
          <mesh
            geometry={nodes.Circle002.geometry}
            material={materials['Frame.001']}
          />
          <mesh
            geometry={nodes.Circle002_1.geometry}
            material={materials.Screen}
          />
          <mesh
            geometry={nodes.Circle002_2.geometry}
            material={materials.ScreenGlass}
          />
          <mesh
            geometry={nodes.Circle002_3.geometry}
            material={materials.Rubber}
          />
          <mesh
            geometry={nodes.Circle002_4.geometry}
            material={materials.DisplayGlass}
          />
          <mesh
            geometry={nodes.AppleLogo000.geometry}
            material={materials['AppleLogo.004']}
            position={[0.005, -0.111, -1.795]}
            scale={0.579}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/model.gltf')

export default forwardRef(Model)
