/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 public/models/spiral.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Spiral(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/spiral.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
    >
      <group name="Scene">
        <mesh
          name="Outer_Spiral"
          geometry={nodes.Outer_Spiral.geometry}
          material={materials['Material.001']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/spiral.glb')
