/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 public/models/v3.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function V3(props) {
  const { nodes, materials } = useGLTF('./models/v3.glb')
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes['outer-spiral'].geometry}
        material={nodes['outer-spiral'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('./models/v3.glb')
